apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: austa-production
  labels:
    app: austa-frontend
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: austa-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
